// Dispatch actions
const SET_SALARY_CALCULATOR_INPUT = "SET_SALARY_CALCULATOR_INPUT";
const SET_SALARY_CALCULATOR_INPUT_TYPE = "SET_SALARY_CALCULATOR_INPUT_TYPE";
const SET_PENSION_PILLAR = "SET_PENSION_PILLAR";
const SET_EMPLOYER_UNEMPLOYMENT_INSURANCE =
  "SET_EMPLOYER_UNEMPLOYMENT_INSURANCE";
const SET_EMPLOYEE_UNEMPLOYMENT_INSURANCE =
  "SET_EMPLOYEE_UNEMPLOYMENT_INSURANCE";

//Regex
const SALARY_INPUT_REGEX = /^\d*\.?\d{0,2}$/; // Matches numbers with up to two decimal places

export {
  SET_SALARY_CALCULATOR_INPUT,
  SET_SALARY_CALCULATOR_INPUT_TYPE,
  SALARY_INPUT_REGEX,
  SET_PENSION_PILLAR,
  SET_EMPLOYER_UNEMPLOYMENT_INSURANCE,
  SET_EMPLOYEE_UNEMPLOYMENT_INSURANCE,
};
